name: Curseforge Build + Upload

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup mod dev workspace
      run: ./gradlew setupDevWorkspace  
    - name: Build
      run: ./gradlew build
    - name: Make Changelog
      run: git log -1 --pretty=%B >> changelog.txt
    - name: Upload
      run: ./gradlew curseforge
      env: 
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
